# Generated by Django 5.2.10 on 2026-03-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteScrapingSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=32)),
                ('selector_key', models.CharField(max_length=128)),
                ('selector_value', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Selector',
                'verbose_name_plural': 'Website Selectors',
                'db_table': 'Website_Scraping_Selectors',
                'ordering': ['website_name', 'selector_key'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=32, unique=True)),
                ('website_full_name', models.CharField(max_length=255)),
                ('start_url', models.CharField(max_length=2048)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Source',
                'verbose_name_plural': 'Website Sources',
                'db_table': 'Website_Scraping_Sources',
                'ordering': ['website_name'],
                'managed': False,
            },
        ),
    ]
