# Generated by Django 5.2.10 on 2026-03-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Professional Category',
                'verbose_name_plural': 'Professional Categories',
                'db_table': 'Professional_Category',
                'ordering': ['category_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('type_of_feedback', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'db_table': 'User_Feedback',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteScrapingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('category', models.CharField(default='Notification', max_length=64)),
                ('website_name', models.CharField(max_length=32)),
                ('detail_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('notice_date', models.CharField(blank=True, max_length=64, null=True)),
                ('due_date', models.CharField(default='-', max_length=64)),
                ('pdf_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('pdf_local_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Scraping Data',
                'verbose_name_plural': 'Website Scraping Data',
                'db_table': 'Website_Scraping_data',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteScrapingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=16)),
                ('total_new_rows', models.IntegerField(default=0)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Scraping Run',
                'verbose_name_plural': 'Website Scraping Runs',
                'db_table': 'Website_Scraping_Runs',
                'ordering': ['-started_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteScrapingRunSiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=32)),
                ('new_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Scraping Run Site Stat',
                'verbose_name_plural': 'Website Scraping Run Site Stats',
                'db_table': 'Website_Scraping_Run_Site_Stats',
                'ordering': ['-new_rows', 'website_name'],
                'managed': False,
            },
        ),
    ]
